import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--next-font-oswald",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--next-font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-inter bg-darkBlack">
        <Navbar />
        <main>
          {children}
        </main>
        
      </body>
    </html>
  );
}
